# Generated by Django 5.0.14 on 2026-09-14 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(default='oxford3000', max_length=100)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('prompt_used', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_words', to='stories.story')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_words', to='stories.word')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='words',
            field=models.ManyToManyField(related_name='stories', through='stories.StoryWord', to='stories.word'),
        ),
        migrations.AddConstraint(
            model_name='storyword',
            constraint=models.UniqueConstraint(fields=('story', 'word'), name='unique_story_word'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['owner', '-created_at'], name='stories_sto_owner_i_8aa2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['owner', 'title'], name='stories_sto_owner_i_3e8149_idx'),
        ),
    ]
