# Generated by Django 5.2.17 on 2026-09-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_word_schema_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='body_th',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='title_th',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
